apiVersion: apps/v1
kind: Deployment
metadata:
 name: webserver
spec:
 replicas: 1
 selector:
  matchLabels:
   app: webserver
 template:
  metadata:
   labels:
    app: webserver
  spec:
   containers:
   - name: webserver
     image: k8sacrcontainer.azurecr.io/k8sacrcontainer:latest
     imagePullPolicy: Always
     ports:
     - containerPort: 80

apiVersion: apps/v1
kind: Service
metadata:
 name: webserver
spec:
 selector:
  app: webserver
 ports:
 -  port: 80
    targetPort: 80
 type: LoadBalancer
