
apiVersion: apps/v1
kind: Deployment
metadata:
 name: webserver
spec:
 replicas: 1
 selector:
  matchLabels:
   app: webserver
 template:
  metadata:
   labels:
    app: webserver
  spec:
   containers:
   - name: my-python-app
     image: k8sacrcontainer.azurecr.io/k8sacrcontainer:latest
     imagePullPolicy: Always
     ports:
     - containerPort: 80

apiVersion: v1
kind: Service
metadata:
 name: webserver
spec:
 selector:
  app: webserver
 ports:
  - protocol: TCP
    port: 80
    targetPort: 80
 type: LoadBalancer
